-- Databricks notebook source
-- MAGIC %md
-- MAGIC #### Silver standardization layer
-- MAGIC One typed and validated table per source dataset. This layer is the target after schema enforcement, casting, standardization, DQ checks, DLQ split, and deduplication.

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_application_train (
  sk_id_curr BIGINT,
  target BIGINT,
  name_contract_type STRING,
  code_gender STRING,
  flag_own_car STRING,
  flag_own_realty STRING,
  cnt_children INT,
  amt_income_total DECIMAL(18,2),
  amt_credit DECIMAL(18,2),
  amt_annuity DECIMAL(18,2),
  amt_goods_price DECIMAL(18,2),
  name_type_suite STRING,
  name_income_type STRING,
  name_education_type STRING,
  name_family_status STRING,
  name_housing_type STRING,
  region_population_relative DOUBLE,
  days_birth INT,
  days_employed INT,
  days_registration INT,
  days_id_publish INT,
  own_car_age INT,
  flag_mobil INT,
  flag_emp_phone INT,
  flag_work_phone INT,
  flag_cont_mobile INT,
  flag_phone INT,
  flag_email INT,
  occupation_type STRING,
  cnt_fam_members INT,
  region_rating_client INT,
  region_rating_client_w_city INT,
  weekday_appr_process_start STRING,
  hour_appr_process_start INT,
  reg_region_not_live_region INT,
  reg_region_not_work_region INT,
  live_region_not_work_region INT,
  reg_city_not_live_city INT,
  reg_city_not_work_city INT,
  live_city_not_work_city INT,
  organization_type STRING,
  ext_source_1 DOUBLE,
  ext_source_2 DOUBLE,
  ext_source_3 DOUBLE,
  apartments_avg DOUBLE,
  basementarea_avg DOUBLE,
  years_beginexpluatation_avg DOUBLE,
  years_build_avg DOUBLE,
  commonarea_avg DOUBLE,
  elevators_avg DOUBLE,
  entrances_avg DOUBLE,
  floorsmax_avg DOUBLE,
  floorsmin_avg DOUBLE,
  landarea_avg DOUBLE,
  livingapartments_avg DOUBLE,
  livingarea_avg DOUBLE,
  nonlivingapartments_avg DOUBLE,
  nonlivingarea_avg DOUBLE,
  apartments_mode DOUBLE,
  basementarea_mode DOUBLE,
  years_beginexpluatation_mode DOUBLE,
  years_build_mode DOUBLE,
  commonarea_mode DOUBLE,
  elevators_mode DOUBLE,
  entrances_mode DOUBLE,
  floorsmax_mode DOUBLE,
  floorsmin_mode DOUBLE,
  landarea_mode DOUBLE,
  livingapartments_mode DOUBLE,
  livingarea_mode DOUBLE,
  nonlivingapartments_mode DOUBLE,
  nonlivingarea_mode DOUBLE,
  apartments_medi DOUBLE,
  basementarea_medi DOUBLE,
  years_beginexpluatation_medi DOUBLE,
  years_build_medi DOUBLE,
  commonarea_medi DOUBLE,
  elevators_medi DOUBLE,
  entrances_medi DOUBLE,
  floorsmax_medi DOUBLE,
  floorsmin_medi DOUBLE,
  landarea_medi DOUBLE,
  livingapartments_medi DOUBLE,
  livingarea_medi DOUBLE,
  nonlivingapartments_medi DOUBLE,
  nonlivingarea_medi DOUBLE,
  fondkapremont_mode STRING,
  housetype_mode STRING,
  totalarea_mode DOUBLE,
  wallsmaterial_mode STRING,
  emergencystate_mode STRING,
  obs_30_cnt_social_circle INT,
  def_30_cnt_social_circle INT,
  obs_60_cnt_social_circle INT,
  def_60_cnt_social_circle INT,
  days_last_phone_change INT,
  flag_document_2 INT,
  flag_document_3 INT,
  flag_document_4 INT,
  flag_document_5 INT,
  flag_document_6 INT,
  flag_document_7 INT,
  flag_document_8 INT,
  flag_document_9 INT,
  flag_document_10 INT,
  flag_document_11 INT,
  flag_document_12 INT,
  flag_document_13 INT,
  flag_document_14 INT,
  flag_document_15 INT,
  flag_document_16 INT,
  flag_document_17 INT,
  flag_document_18 INT,
  flag_document_19 INT,
  flag_document_20 INT,
  flag_document_21 INT,
  amt_req_credit_bureau_hour DECIMAL(18,2),
  amt_req_credit_bureau_day DECIMAL(18,2),
  amt_req_credit_bureau_week DECIMAL(18,2),
  amt_req_credit_bureau_mon DECIMAL(18,2),
  amt_req_credit_bureau_qrt DECIMAL(18,2),
  amt_req_credit_bureau_year DECIMAL(18,2),
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_application_test (
  sk_id_curr BIGINT,
  name_contract_type STRING,
  code_gender STRING,
  flag_own_car STRING,
  flag_own_realty STRING,
  cnt_children INT,
  amt_income_total DECIMAL(18,2),
  amt_credit DECIMAL(18,2),
  amt_annuity DECIMAL(18,2),
  amt_goods_price DECIMAL(18,2),
  name_type_suite STRING,
  name_income_type STRING,
  name_education_type STRING,
  name_family_status STRING,
  name_housing_type STRING,
  region_population_relative DOUBLE,
  days_birth INT,
  days_employed INT,
  days_registration INT,
  days_id_publish INT,
  own_car_age INT,
  flag_mobil INT,
  flag_emp_phone INT,
  flag_work_phone INT,
  flag_cont_mobile INT,
  flag_phone INT,
  flag_email INT,
  occupation_type STRING,
  cnt_fam_members INT,
  region_rating_client INT,
  region_rating_client_w_city INT,
  weekday_appr_process_start STRING,
  hour_appr_process_start INT,
  reg_region_not_live_region INT,
  reg_region_not_work_region INT,
  live_region_not_work_region INT,
  reg_city_not_live_city INT,
  reg_city_not_work_city INT,
  live_city_not_work_city INT,
  organization_type STRING,
  ext_source_1 DOUBLE,
  ext_source_2 DOUBLE,
  ext_source_3 DOUBLE,
  apartments_avg DOUBLE,
  basementarea_avg DOUBLE,
  years_beginexpluatation_avg DOUBLE,
  years_build_avg DOUBLE,
  commonarea_avg DOUBLE,
  elevators_avg DOUBLE,
  entrances_avg DOUBLE,
  floorsmax_avg DOUBLE,
  floorsmin_avg DOUBLE,
  landarea_avg DOUBLE,
  livingapartments_avg DOUBLE,
  livingarea_avg DOUBLE,
  nonlivingapartments_avg DOUBLE,
  nonlivingarea_avg DOUBLE,
  apartments_mode DOUBLE,
  basementarea_mode DOUBLE,
  years_beginexpluatation_mode DOUBLE,
  years_build_mode DOUBLE,
  commonarea_mode DOUBLE,
  elevators_mode DOUBLE,
  entrances_mode DOUBLE,
  floorsmax_mode DOUBLE,
  floorsmin_mode DOUBLE,
  landarea_mode DOUBLE,
  livingapartments_mode DOUBLE,
  livingarea_mode DOUBLE,
  nonlivingapartments_mode DOUBLE,
  nonlivingarea_mode DOUBLE,
  apartments_medi DOUBLE,
  basementarea_medi DOUBLE,
  years_beginexpluatation_medi DOUBLE,
  years_build_medi DOUBLE,
  commonarea_medi DOUBLE,
  elevators_medi DOUBLE,
  entrances_medi DOUBLE,
  floorsmax_medi DOUBLE,
  floorsmin_medi DOUBLE,
  landarea_medi DOUBLE,
  livingapartments_medi DOUBLE,
  livingarea_medi DOUBLE,
  nonlivingapartments_medi DOUBLE,
  nonlivingarea_medi DOUBLE,
  fondkapremont_mode STRING,
  housetype_mode STRING,
  totalarea_mode DOUBLE,
  wallsmaterial_mode STRING,
  emergencystate_mode STRING,
  obs_30_cnt_social_circle INT,
  def_30_cnt_social_circle INT,
  obs_60_cnt_social_circle INT,
  def_60_cnt_social_circle INT,
  days_last_phone_change INT,
  flag_document_2 INT,
  flag_document_3 INT,
  flag_document_4 INT,
  flag_document_5 INT,
  flag_document_6 INT,
  flag_document_7 INT,
  flag_document_8 INT,
  flag_document_9 INT,
  flag_document_10 INT,
  flag_document_11 INT,
  flag_document_12 INT,
  flag_document_13 INT,
  flag_document_14 INT,
  flag_document_15 INT,
  flag_document_16 INT,
  flag_document_17 INT,
  flag_document_18 INT,
  flag_document_19 INT,
  flag_document_20 INT,
  flag_document_21 INT,
  amt_req_credit_bureau_hour DECIMAL(18,2),
  amt_req_credit_bureau_day DECIMAL(18,2),
  amt_req_credit_bureau_week DECIMAL(18,2),
  amt_req_credit_bureau_mon DECIMAL(18,2),
  amt_req_credit_bureau_qrt DECIMAL(18,2),
  amt_req_credit_bureau_year DECIMAL(18,2),
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_bureau (
  sk_id_curr BIGINT,
  sk_bureau_id BIGINT,
  credit_active STRING,
  credit_currency STRING,
  days_credit INT,
  credit_day_overdue INT,
  days_credit_enddate INT,
  days_enddate_fact INT,
  amt_credit_max_overdue DECIMAL(18,2),
  cnt_credit_prolong INT,
  amt_credit_sum DECIMAL(18,2),
  amt_credit_sum_debt DECIMAL(18,2),
  amt_credit_sum_limit DECIMAL(18,2),
  amt_credit_sum_overdue DECIMAL(18,2),
  credit_type STRING,
  days_credit_update INT,
  amt_annuity DECIMAL(18,2),
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_bureau_balance (
  sk_bureau_id BIGINT,
  months_balance INT,
  status STRING,
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_previous_application (
  sk_id_prev BIGINT,
  sk_id_curr BIGINT,
  name_contract_type STRING,
  amt_annuity DECIMAL(18,2),
  amt_application DECIMAL(18,2),
  amt_credit DECIMAL(18,2),
  amt_down_payment DECIMAL(18,2),
  amt_goods_price DECIMAL(18,2),
  weekday_appr_process_start STRING,
  hour_appr_process_start INT,
  flag_last_appl_per_contract STRING,
  nflag_last_appl_in_day INT,
  nflag_micro_cash INT,
  rate_down_payment DOUBLE,
  rate_interest_primary DOUBLE,
  rate_interest_privileged DOUBLE,
  name_cash_loan_purpose STRING,
  name_contract_status STRING,
  days_decision INT,
  name_payment_type STRING,
  code_reject_reason STRING,
  name_type_suite STRING,
  name_client_type STRING,
  name_goods_category STRING,
  name_portfolio STRING,
  name_product_type STRING,
  channel_type STRING,
  sellerplace_area INT,
  name_seller_industry STRING,
  cnt_payment INT,
  name_yield_group STRING,
  product_combination STRING,
  days_first_drawing INT,
  days_first_due INT,
  days_last_due_1st_version INT,
  days_last_due INT,
  days_termination INT,
  nflag_insured_on_approval INT,
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_pos_cash_balance (
  sk_id_prev BIGINT,
  sk_id_curr BIGINT,
  months_balance INT,
  cnt_instalment INT,
  cnt_instalment_future INT,
  name_contract_status STRING,
  sk_dpd INT,
  sk_dpd_def INT,
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_credit_card_balance (
  sk_id_prev BIGINT,
  sk_id_curr BIGINT,
  months_balance INT,
  amt_balance DECIMAL(18,2),
  amt_credit_limit_actual DECIMAL(18,2),
  amt_drawings_atm_current DECIMAL(18,2),
  amt_drawings_current DECIMAL(18,2),
  amt_drawings_other_current DECIMAL(18,2),
  amt_drawings_pos_current DECIMAL(18,2),
  amt_inst_min_regularity DECIMAL(18,2),
  amt_payment_current DECIMAL(18,2),
  amt_payment_total_current DECIMAL(18,2),
  amt_receivable_principal DECIMAL(18,2),
  amt_recivable DECIMAL(18,2),
  amt_total_receivable DECIMAL(18,2),
  cnt_drawings_atm_current INT,
  cnt_drawings_current INT,
  cnt_drawings_other_current INT,
  cnt_drawings_pos_current INT,
  cnt_instalment_mature_cum INT,
  name_contract_status STRING,
  sk_dpd INT,
  sk_dpd_def INT,
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_installments_payments (
  sk_id_prev BIGINT,
  sk_id_curr BIGINT,
  num_instalment_version INT,
  num_instalment_number INT,
  days_instalment INT,
  days_entry_payment INT,
  amt_instalment DECIMAL(18,2),
  amt_payment DECIMAL(18,2),
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);

-- COMMAND ----------

CREATE TABLE IF NOT EXISTS credit_risk_dev.silver.standardized_column_description (
  source_table STRING,
  source_column STRING,
  column_description STRING,
  special_note STRING,
  source_file_name STRING,
  source_file_path STRING,
  pipeline_run_id STRING,
  ingestion_timestamp TIMESTAMP,
  standardization_timestamp TIMESTAMP,
  standardization_date DATE
)
USING DELTA
PARTITIONED BY (standardization_date);
